const {name1, name2} = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-syntax')
require('./7-mind-grenade')
sayHi(name1)
sayHi(name2)
sayHi('Nobody')
console.log(data)